"""Assemble everything the PDF template prints, from guv_calcs objects only.

All numbers are computed here; the template formats. Pathogen figures use
room.average_value (per-species mean kinetics per wavelength, additive across
the lamps' wavelengths) exactly like /disinfection-table. Hours to the limit use
the spectrally weighted dose shared with check-lamps.
"""
from __future__ import annotations

from pathlib import Path
import math
import re
from dataclasses import dataclass, field
from decimal import Decimal, ROUND_HALF_UP
from datetime import datetime
from typing import Any, Optional

import numpy as np
from guv_calcs import WHOLE_ROOM_FLUENCE, EYE_LIMITS, SKIN_LIMITS

from api.v1.safety_helpers import HoursToLimit, hours_to_limit_by_standard
from api.v1.session_schemas import ReportRequest, ReportMeta, ReportOptions
from api.v1.session_helpers import _standard_to_label
from api.v1.lamp_routers import LAMP_DISPLAY_NAMES

# The app's automatic instance names ("Lamp 3"); not a fixture name
_AUTO_LAMP_NAME = re.compile(r"^Lamp \d+$")
# IES keyword values that mean "not filled in"
_PLACEHOLDER_KEYWORDS = {"unknown", "n/a", "na", "none", "-", "tbd"}

STANDARD_IDS = {WHOLE_ROOM_FLUENCE, SKIN_LIMITS, EYE_LIMITS}
EFFICACY_FUNCTIONS = ("each_uv", "cadr_lps", "cadr_cfm", "log1", "log2", "log3")


class ReportDataError(ValueError):
    """The request names data the room cannot supply (e.g. a species with no
    inactivation data at the lamps' wavelengths). The endpoint answers 422."""


@dataclass(frozen=True)
class Versions:
    app: str
    guv_calcs: str


@dataclass(frozen=True)
class Units:
    length: str      # "m" | "ft"
    area: str        # "m²" | "ft²"
    volume: str      # "m³" | "ft³"


@dataclass(frozen=True)
class Stats:
    mean: Optional[float]
    max: Optional[float]
    min: Optional[float]


@dataclass(frozen=True)
class RoomInfo:
    name: str
    x: float
    y: float
    z: float
    floor_area: float
    volume: float
    shape: str            # "rectangle" | "polygon"
    vertex_count: int
    air_changes: float
    reflectance_enabled: bool


@dataclass(frozen=True)
class SurfaceRow:
    name: str
    reflectance: float


@dataclass(frozen=True)
class LampRow:
    lamp_id: str
    name: str
    fixture: str
    type_label: str               # "222 nm" | "254 nm" | "Custom wavelength (265 nm)"
    wavelength: Optional[float]
    output_percent: float
    position: tuple[float, float, float]
    aim: tuple[float, float, float]
    heading: float
    bank: float
    enabled: bool


@dataclass(frozen=True)
class ObjectRow:
    name: str
    size: tuple[float, float, float]
    base_centre: tuple[float, float, float]
    yaw: float
    reflectance: float
    transmittance: float
    enabled: bool


@dataclass(frozen=True)
class PathogenRow:
    species: str
    category: str
    each_uv: float
    cadr_lps: float
    cadr_cfm: float
    t90: Optional[float]
    t99: Optional[float]
    t999: Optional[float]


@dataclass(frozen=True)
class LampSafetyRow:
    name: str
    skin_dose: float
    skin_tlv: float
    eye_dose: float
    eye_tlv: float
    compliant: bool
    dimming_note: Optional[str]   # "Dim to 71% (minimum 79%)" or None
    missing_spectrum: bool


@dataclass(frozen=True)
class Occupancy:
    headline_hours: Optional[float]
    headline_name: str            # "ACGIH TLV" | "ICNIRP limit"
    unlimited: bool
    statement: str


@dataclass(frozen=True)
class SafetyInfo:
    standard_label: str
    hours: dict[str, HoursToLimit]
    skin: Stats
    eye: Stats
    skin_irradiance: Stats        # µW/cm² behind the 8 h doses
    eye_irradiance: Stats
    lamps: list[LampSafetyRow]
    warnings: list[str]
    occupancy: Occupancy
    has_222nm: bool               # ozone is only generated by 222 nm sources
    air_changes: float            # ventilation, per hour
    ozone_decay_constant: Optional[float]
    ozone_ppb: Optional[float]    # None without 222 nm sources


@dataclass(frozen=True)
class Summary:
    each_uv: Optional[float]
    cadr_lps: Optional[float]
    cadr_cfm: Optional[float]
    avg_fluence: Optional[float]
    lead_species: Optional[str]


@dataclass(frozen=True)
class FluenceInfo:
    stats: Stats
    wavelengths_used: list[int]
    wavelengths_missing: list[int]
    image_key: str
    levels: list[float]           # isosurface levels drawn in the capture (see report_iso_levels)
    by_wavelength: dict[int, float]  # average fluence per lamp wavelength (µW/cm²)


def report_iso_levels(mean: Optional[float]) -> list[float]:
    """Isosurface levels the frontend draws for a report capture: half, once and
    twice the zone's average, each to two significant figures. Mirrors
    `reportIsoLevels` in ui/src/lib/utils/reportCapture.ts."""
    if mean is None or not math.isfinite(mean) or mean <= 0:
        return []
    levels = []
    for k in (0.5, 1.0, 2.0):
        # Two significant figures, rounding halves up like JavaScript's toPrecision
        d = Decimal(str(mean * k))
        quantum = Decimal(1).scaleb(d.adjusted() - 1)
        levels.append(float(d.quantize(quantum, rounding=ROUND_HALF_UP)))
    return levels


@dataclass(frozen=True)
class PlaneZone:
    zone_id: str
    name: str
    height: Optional[float]
    units: str
    exposure: Optional[str]       # "2 h dose" when dose mode
    stats: Stats
    svg: str = ""                 # filled by plots.py


@dataclass(frozen=True)
class VolumeZone:
    zone_id: str
    name: str
    units: str
    exposure: Optional[str]
    stats: Stats
    image_key: str


@dataclass(frozen=True)
class PointZone:
    zone_id: str
    name: str
    position: tuple[float, float, float]
    units: str
    value: Optional[float]


@dataclass(frozen=True)
class LampTypeInfo:
    fixture: str
    wavelength: Optional[float]
    lamp_id: str                  # representative lamp for plotting
    has_spectrum: bool


@dataclass
class ReportContext:
    meta: ReportMeta
    options: ReportOptions
    generated_at: datetime
    versions: Versions
    page_size: str                # "A4" | "Letter"
    units: Units
    precision: int
    images: dict[str, bytes]
    room: RoomInfo
    surfaces: list[SurfaceRow]
    lamps: list[LampRow]
    objects: list[ObjectRow]
    summary: Summary
    safety: SafetyInfo
    pathogens: list[PathogenRow]
    fluence: FluenceInfo
    custom_planes: list[PlaneZone]
    custom_volumes: list[VolumeZone]
    custom_points: list[PointZone]
    lamp_types: list[LampTypeInfo]
    skin_svg: str = ""
    eye_svg: str = ""
    survival_svg: str = ""
    lamp_plots: dict[str, tuple[str, str]] = field(default_factory=dict)  # fixture → (polar svg, spectrum svg)
    # The room's InactivationData for the whole-room zone. Building one runs the
    # kinetics over the entire dataset (~0.7 s), so it is built once here and
    # reused by the survival plot instead of letting room.survival_plot rebuild it.
    efficacy_data: Any = field(default=None, repr=False)


# ----------------------------------------------------------------------------
# helpers
# ----------------------------------------------------------------------------

def _finite(v) -> Optional[float]:
    try:
        f = float(v)
    except (TypeError, ValueError):
        return None
    return f if math.isfinite(f) else None


def _stats(zone) -> Stats:
    values = zone.get_values() if zone is not None else None
    if values is None:
        return Stats(None, None, None)
    arr = np.asarray(values, dtype=float)
    arr = arr[np.isfinite(arr)]
    if arr.size == 0:
        return Stats(None, None, None)
    return Stats(float(arr.mean()), float(arr.max()), float(arr.min()))


def _is_feet(room) -> bool:
    return "feet" in str(room.dim.units).lower() or "ft" == str(room.dim.units).lower()


def _units(room) -> Units:
    return Units("ft", "ft²", "ft³") if _is_feet(room) else Units("m", "m²", "m³")


def _page_size(room, options: ReportOptions) -> str:
    if options.page_size == "a4":
        return "A4"
    if options.page_size == "letter":
        return "Letter"
    return "Letter" if _is_feet(room) else "A4"


def _exposure_label(zone) -> Optional[str]:
    if not zone.dose:
        return None
    secs = zone.exposure_time.total_seconds()
    hours = secs / 3600
    if hours >= 1 and abs(hours - round(hours)) < 1e-9:
        return f"{int(round(hours))} h dose"
    if secs >= 60 and abs(secs / 60 - round(secs / 60)) < 1e-9:
        return f"{int(round(secs / 60))} min dose"
    return f"{secs:g} s dose"


def _zone_units(zone) -> str:
    return "mJ/cm²" if zone.dose else "µW/cm²"


def _fixture_name(lamp, given: str | None = None) -> str:
    """Preset display name. For a custom fixture, in order: the model name the
    browser sent (its custom-lamp definition or IES filename), the user's own
    lamp name, the IES file's [LUMINAIRE] keyword, the photometric file's name,
    else "Custom fixture"."""
    preset = getattr(lamp, "preset_id", None)
    if preset and preset != "custom":
        return LAMP_DISPLAY_NAMES.get(str(preset), str(preset).replace("_", " ").title())
    if given and given.strip():
        return given.strip()
    name = str(getattr(lamp, "name", "") or "").strip()
    if name and not _AUTO_LAMP_NAME.match(name):
        return name
    # lamp.keywords is guv_calcs's preset list; the IES header's own keywords sit on lamp.ies
    keywords = getattr(getattr(getattr(lamp, "ies", None), "header", None), "keywords", None)
    luminaire = str(keywords.get("LUMINAIRE") or "").strip() if isinstance(keywords, dict) else ""
    if luminaire and luminaire.lower() not in _PLACEHOLDER_KEYWORDS:
        return luminaire
    filedata = getattr(lamp, "filedata", None)
    if isinstance(filedata, (str, Path)) and str(filedata):
        return Path(str(filedata)).name
    return "Custom fixture"


def _type_label(lamp) -> str:
    """The lamp's kind for a reader: 222 nm, 254 nm, or a custom wavelength
    (user-specified, or the peak of the uploaded spectrum)."""
    guv = str(getattr(getattr(lamp, "guv_type", None), "value", "") or "").lower()
    if guv == "krcl":
        return "222 nm"
    if guv == "lphg":
        return "254 nm"
    wavelength = _finite(getattr(lamp, "wavelength", None))
    spectrum = getattr(lamp, "spectrum", None)
    if wavelength is None and spectrum is not None:
        wavelength = _finite(getattr(spectrum, "peak_wavelength", None))
    if wavelength is None:
        return "Custom wavelength"
    return f"Custom wavelength ({wavelength:g} nm)"


def _dimming_note(skin_dim: float, eye_dim: float) -> Optional[str]:
    d = min(skin_dim, eye_dim)
    if d >= 1:
        return None
    minimum = math.floor(d * 100)
    suggested = max(math.floor(d * 0.9 * 100), 0)
    if suggested >= minimum:
        suggested = minimum - 1
    return f"Dim to {suggested}% (minimum {minimum}%)"


def _occupancy(hours: dict[str, HoursToLimit], standard_label: str) -> Occupancy:
    uses_icnirp = "ICNIRP" in standard_label
    h = hours["ICNIRP" if uses_icnirp else "ACGIH"]
    candidates = [v for v in (h.skin, h.eye) if v is not None]
    headline = min(candidates) if candidates else None
    name = "ICNIRP limit" if uses_icnirp else "ACGIH TLV"
    if headline is None:
        return Occupancy(None, name, False, "Occupancy limit could not be evaluated")
    if headline >= 8:
        return Occupancy(headline, name, True, f"Continuous occupancy is within the {name}")
    return Occupancy(headline, name, False, f"Safe to occupy for {headline:.1f} hours per day ({name})")


def _dose_to_irradiance(s: Stats) -> Stats:
    """8 h dose (mJ/cm²) → irradiance (µW/cm²)."""
    def f(v):
        return None if v is None else v * 1000 / (8 * 3600)
    return Stats(f(s.mean), f(s.max), f(s.min))


# ----------------------------------------------------------------------------
# sections
# ----------------------------------------------------------------------------

def _room_info(room) -> RoomInfo:
    d = room.dim
    poly = d.polygon
    vertices = getattr(poly, "vertices", None)
    return RoomInfo(
        name=room.name, x=float(d.x), y=float(d.y), z=float(d.z),
        floor_area=float(poly.area), volume=float(room.volume),
        shape="polygon" if d.is_polygon else "rectangle",
        vertex_count=len(vertices) if vertices is not None else 4,
        air_changes=float(room.air_changes),
        reflectance_enabled=bool(room.ref_manager.enabled),
    )


def _surfaces(room) -> list[SurfaceRow]:
    return [SurfaceRow(k.replace("_", " ").title(), float(v.R)) for k, v in room.surfaces.items()]


def _lamps(room, fixture_names: dict[str, str]) -> list[LampRow]:
    return [
        LampRow(
            lamp_id=str(lid), name=lamp.name, fixture=_fixture_name(lamp, fixture_names.get(str(lid))),
            type_label=_type_label(lamp),
            wavelength=_finite(lamp.wavelength), output_percent=float(lamp.scaling_factor) * 100,
            position=(float(lamp.x), float(lamp.y), float(lamp.z)),
            aim=(float(lamp.aimx), float(lamp.aimy), float(lamp.aimz)),
            heading=float(lamp.heading), bank=float(lamp.bank), enabled=bool(lamp.enabled),
        )
        for lid, lamp in room.lamps.items()
    ]


def _objects(room) -> list[ObjectRow]:
    rows = []
    for obj in getattr(room, "objects", {}).values():
        data = obj.to_dict()
        rows.append(ObjectRow(
            name=obj.name, size=(float(obj.width), float(obj.length), float(obj.height)),
            base_centre=(float(obj.x), float(obj.y), float(obj.z)), yaw=float(data.get("yaw", 0.0) or 0.0),
            reflectance=float(obj.R), transmittance=float(obj.T), enabled=bool(obj.enabled),
        ))
    return rows


def _as_dict(value, species: list[str]) -> dict:
    """room.average_value returns a float for one species and a dict for a list."""
    if isinstance(value, dict):
        return value
    return {species[0]: value} if len(species) == 1 else {}


def _pathogens(room, species: list[str]) -> tuple[list[PathogenRow], FluenceInfo, Any]:
    """Pathogen rows, fluence info, and the InactivationData they came from."""
    wrf = room.calc_zones.get(WHOLE_ROOM_FLUENCE)
    stats = _stats(wrf)
    fluence_dict = wrf.calculator.cache.by_wavelength(room.lamps, reduce=np.mean) if wrf is not None else {}
    data = room.get_efficacy_data(WHOLE_ROOM_FLUENCE)
    base = data.base_df
    available = {int(w) for w in base["wavelength [nm]"].unique()}
    used = sorted(int(w) for w in fluence_dict if int(w) in available)
    missing = sorted(int(w) for w in fluence_dict if int(w) not in available)
    rows: list[PathogenRow] = []
    if species and not used:
        raise ReportDataError(f"No inactivation data for '{species[0]}' at the lamps' wavelengths")
    if used and species:
        # Validate up front: guv_calcs raises an unnamed "No data available for
        # wavelength" error when any requested species lacks a wavelength.
        wavelengths_of = base.groupby("Species")["wavelength [nm]"].apply(lambda s: {int(w) for w in s}).to_dict()
        for sp in species:
            if not set(used) <= wavelengths_of.get(sp, set()):
                raise ReportDataError(f"No inactivation data for '{sp}' at the lamps' wavelengths")
        # room.average_value would build a fresh InactivationData per call; the
        # one above already holds the computed columns for every species
        values = {
            fn: _as_dict(data.average_value(function=fn, species=species), species)
            for fn in EFFICACY_FUNCTIONS
        }
        cats = base.drop_duplicates("Species").set_index("Species")["Category"].to_dict()
        for sp in species:
            each = _finite(values["each_uv"].get(sp))
            if each is None:
                raise ReportDataError(f"No inactivation data for '{sp}' at the lamps' wavelengths")
            rows.append(PathogenRow(
                species=sp, category=str(cats.get(sp, "")), each_uv=each,
                cadr_lps=_finite(values["cadr_lps"].get(sp)) or 0.0,
                cadr_cfm=_finite(values["cadr_cfm"].get(sp)) or 0.0,
                t90=_finite(values["log1"].get(sp)), t99=_finite(values["log2"].get(sp)),
                t999=_finite(values["log3"].get(sp)),
            ))
    return rows, FluenceInfo(stats=stats, wavelengths_used=used, wavelengths_missing=missing,
                             image_key=f"volume:{WHOLE_ROOM_FLUENCE}", levels=report_iso_levels(stats.mean),
                             by_wavelength={int(w): float(v) for w, v in fluence_dict.items()}), data


def _safety(room) -> SafetyInfo:
    skin = room.calc_zones.get(SKIN_LIMITS)
    eye = room.calc_zones.get(EYE_LIMITS)
    label = _standard_to_label(room.standard)
    hours = hours_to_limit_by_standard(room)
    result = room.check_lamps()
    lamps = [
        LampSafetyRow(
            name=r.lamp_name, skin_dose=float(r.skin_dose_max), skin_tlv=float(r.skin_tlv),
            eye_dose=float(r.eye_dose_max), eye_tlv=float(r.eye_tlv),
            compliant=bool(r.is_skin_compliant and r.is_eye_compliant),
            dimming_note=_dimming_note(r.skin_dimming_required, r.eye_dimming_required),
            missing_spectrum=bool(r.missing_spectrum),
        )
        for r in result.lamp_results.values()
    ]
    warnings = [w.message for w in result.warnings if not w.lamp_id]
    skin_stats, eye_stats = _stats(skin), _stats(eye)
    has_222 = any(_finite(l.wavelength) == 222 for l in room.lamps.values())
    ozone = _finite(room.estimate_ozone_increase()) if has_222 else None
    return SafetyInfo(
        standard_label=label, hours=hours, skin=skin_stats, eye=eye_stats,
        skin_irradiance=_dose_to_irradiance(skin_stats), eye_irradiance=_dose_to_irradiance(eye_stats),
        lamps=lamps, warnings=warnings, occupancy=_occupancy(hours, label),
        has_222nm=has_222, air_changes=float(room.air_changes),
        ozone_decay_constant=_finite(getattr(room, "ozone_decay_constant", None)), ozone_ppb=ozone,
    )


def _point_position(zone) -> tuple[float, float, float]:
    g = zone.geometry
    for attr in ("position", "point"):
        p = getattr(g, attr, None)
        if p is not None:
            arr = np.ravel(np.asarray(p, dtype=float))
            if arr.size >= 3:
                return (float(arr[0]), float(arr[1]), float(arr[2]))
    if all(hasattr(g, a) for a in ("x", "y", "z")):
        return (float(np.ravel(g.x)[0]), float(np.ravel(g.y)[0]), float(np.ravel(g.z)[0]))
    pts = np.asarray(getattr(g, "points", np.zeros(3)), dtype=float).reshape(-1, 3)
    return (float(pts[0][0]), float(pts[0][1]), float(pts[0][2]))


def _custom_zones(room) -> tuple[list[PlaneZone], list[VolumeZone], list[PointZone]]:
    planes, vols, pts = [], [], []
    for zid, z in room.calc_zones.items():
        if zid in STANDARD_IDS or z.get_values() is None:
            continue
        ct = z.calctype.lower()
        if ct == "plane":
            planes.append(PlaneZone(zid, z.name, _finite(getattr(z.geometry, "height", None)),
                                    _zone_units(z), _exposure_label(z), _stats(z)))
        elif ct == "volume":
            vols.append(VolumeZone(zid, z.name, _zone_units(z), _exposure_label(z), _stats(z), f"volume:{zid}"))
        else:
            pts.append(PointZone(zid, z.name, _point_position(z), _zone_units(z),
                                 _finite(np.ravel(z.get_values())[0])))
    return planes, vols, pts


def _lamp_types(room, fixture_names: dict[str, str]) -> list[LampTypeInfo]:
    seen: dict[str, LampTypeInfo] = {}
    for lid, lamp in room.lamps.items():
        fx = _fixture_name(lamp, fixture_names.get(str(lid)))
        if fx not in seen:
            seen[fx] = LampTypeInfo(fx, _finite(lamp.wavelength), str(lid), lamp.spectrum is not None)
    return list(seen.values())


def build_report_context(room, request: ReportRequest, images: dict[str, bytes], versions: Versions) -> ReportContext:
    pathogens, fluence, efficacy_data = _pathogens(room, list(request.pathogens))
    lead = pathogens[0] if pathogens else None
    planes, vols, pts = _custom_zones(room)
    return ReportContext(
        meta=request.meta, options=request.options, generated_at=datetime.now(), versions=versions,
        page_size=_page_size(room, request.options), units=_units(room),
        precision=max(int(getattr(room, "precision", 1) or 1), 1), images=images,
        room=_room_info(room), surfaces=_surfaces(room), lamps=_lamps(room, request.fixture_names), objects=_objects(room),
        summary=Summary(
            each_uv=lead.each_uv if lead else None, cadr_lps=lead.cadr_lps if lead else None,
            cadr_cfm=lead.cadr_cfm if lead else None, avg_fluence=fluence.stats.mean,
            lead_species=lead.species if lead else None,
        ),
        safety=_safety(room), pathogens=pathogens, fluence=fluence,
        custom_planes=planes, custom_volumes=vols, custom_points=pts, lamp_types=_lamp_types(room, request.fixture_names),
        efficacy_data=efficacy_data,
    )
